
theme: jekyll-theme-slate
title: Machine learning based cyber attacks targeting on controlled information 

# Short description (goes below the title; it will also be used in the RSS feed)
# description:  Everything about the datasets and data sources mentioned in the survey paper "Data-driven cyber security incident prediction".
